name: ci:test

on:
  push:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"
  pull_request:
    branches:
      - main
    paths-ignore:
      - "docs/**"
      - "**.md"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout current state"
        uses: actions/checkout@v3
      - shell: bash
        run: |
          rc=/tmp/rcfile
          echo 'shopt -s expand_aliases' > $rc
          echo 'alias docker-compose="docker compose" ' >> $rc
      - name: "Save Python and Node versions to env"
        run: |
          echo "PYTHON_VERSION=$(cat '.python-version')" >> ${GITHUB_ENV}
          echo "NODE_VERSION=$(cat '.nvmrc')" >> ${GITHUB_ENV}
      - name: "Set up Python"
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: "Set up Node"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: "Install invenio-cli"
        run: |
          pip install --no-cache-dir --upgrade pip invenio-cli pipenv
      - name: "Install XMLSec1 Dependency for Ultraviolet SAML"
        run: |
          sudo apt-get update -y
          sudo apt-get install -y libxml2-dev libxmlsec1-dev
      - name: "Setup mandatory files"
        run: |
          echo -e "[cli]\nproject_dir = "$PWD"\nservices_setup = False" >> .invenio.private
          echo -e FLASK_SECRET_KEY="some random value" >> .env
      - name: "Install project dependencies"
        run: |
          invenio-cli packages lock --pre --dev
          invenio-cli install --pre --dev
          pipenv run pip install -U jsonschema==4.17.3
      - name: Start services and app
        run: |
          docker -v
          docker compose up -d
          invenio-cli run &
          pipenv run invenio db create
      - name: "Run tests"
        run: |
          E2E=no pipenv run pytest -p no:cacheprovider
